"""
Classification result model.

Contains the ClassificationResult dataclass representing output from
the LLM classification service (Claude Sonnet).
"""

from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional
import json


@dataclass
class ClassificationResult:
    """
    Result from LLM classification service.

    Attributes:
        template_name: Name of the selected template (e.g., "task", "journal", "general").
        confidence: Classification confidence score from 0.0 to 1.0.
        fields: Dictionary of extracted field values for the selected template.
        title: Suggested page title generated by the LLM.
        tags: List of topic tags generated by the LLM.
        reasoning: Optional explanation of the classification decision.
    """
    template_name: str
    confidence: float
    fields: Dict[str, Any]
    title: str
    tags: List[str]
    reasoning: Optional[str] = None

    def __post_init__(self) -> None:
        """Validate fields after initialization."""
        if not isinstance(self.template_name, str) or not self.template_name:
            raise ValueError("template_name must be a non-empty string")
        if not isinstance(self.confidence, (int, float)):
            raise ValueError("confidence must be a number")
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError("confidence must be between 0.0 and 1.0")
        if not isinstance(self.fields, dict):
            raise ValueError("fields must be a dictionary")
        if not isinstance(self.title, str):
            raise ValueError("title must be a string")
        if not isinstance(self.tags, list):
            raise ValueError("tags must be a list")
        if not all(isinstance(tag, str) for tag in self.tags):
            raise ValueError("all tags must be strings")
        if self.reasoning is not None and not isinstance(self.reasoning, str):
            raise ValueError("reasoning must be a string or None")

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert to dictionary for JSON serialization.

        Returns:
            Dictionary representation suitable for database storage.
        """
        return asdict(self)

    def to_json(self) -> str:
        """
        Serialize to JSON string.

        Returns:
            JSON string representation.
        """
        return json.dumps(self.to_dict())

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ClassificationResult":
        """
        Create instance from dictionary.

        Args:
            data: Dictionary with classification result fields.

        Returns:
            New ClassificationResult instance.

        Raises:
            KeyError: If required fields are missing.
            ValueError: If field types are invalid.
        """
        return cls(
            template_name=data["template_name"],
            confidence=float(data["confidence"]),
            fields=data.get("fields", {}),
            title=data["title"],
            tags=list(data.get("tags", [])),
            reasoning=data.get("reasoning"),
        )

    @classmethod
    def from_json(cls, json_str: str) -> "ClassificationResult":
        """
        Deserialize from JSON string.

        Args:
            json_str: JSON string representation.

        Returns:
            New ClassificationResult instance.
        """
        return cls.from_dict(json.loads(json_str))

    @classmethod
    def from_llm_response(cls, response: Dict[str, Any]) -> "ClassificationResult":
        """
        Create instance from Claude API JSON response.

        The expected response format from the LLM is:
        {
            "template": "template_name",
            "confidence": 0.0-1.0,
            "reasoning": "explanation",
            "title": "suggested title",
            "tags": ["tag1", "tag2"],
            "fields": { ... }
        }

        Args:
            response: Parsed JSON response from Claude API.

        Returns:
            New ClassificationResult instance.
        """
        return cls(
            template_name=response["template"],
            confidence=float(response["confidence"]),
            fields=response.get("fields", {}),
            title=response["title"],
            tags=list(response.get("tags", [])),
            reasoning=response.get("reasoning"),
        )

    def is_above_threshold(self, threshold: float = 0.7) -> bool:
        """
        Check if confidence meets the classification threshold.

        Args:
            threshold: Minimum confidence required (default 0.7 per PRD).

        Returns:
            True if confidence >= threshold.
        """
        return self.confidence >= threshold

    def is_fallback(self) -> bool:
        """
        Check if this is a fallback to general template.

        Returns:
            True if template_name is "general".
        """
        return self.template_name == "general"

    def get_field(self, field_name: str, default: Any = None) -> Any:
        """
        Get a specific extracted field value.

        Args:
            field_name: Name of the field to retrieve.
            default: Default value if field not found.

        Returns:
            Field value or default.
        """
        return self.fields.get(field_name, default)

    @classmethod
    def create_fallback(
        cls,
        title: str,
        transcript_text: str,
        tags: Optional[List[str]] = None,
    ) -> "ClassificationResult":
        """
        Create a fallback classification result when LLM classification fails
        or confidence is below threshold.

        Args:
            title: Title to use (typically first sentence of transcript).
            transcript_text: The original transcript text.
            tags: Optional tags to include.

        Returns:
            ClassificationResult with template_name="general" and confidence=0.0.
        """
        return cls(
            template_name="general",
            confidence=0.0,
            fields={"summary": transcript_text[:500] if len(transcript_text) > 500 else transcript_text},
            title=title,
            tags=tags or [],
            reasoning="Fallback classification used (LLM classification failed or below threshold)",
        )
